language: objective-c
compiler:
  - clang
git:
  submodules: false
before_install:
  - sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
before_script:
  - git clone git://github.com/shotamatsuda/algorithm.git ../algorithm
  - git clone git://github.com/shotamatsuda/math.git ../math
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
notifications:
  slack:
    secure: EkRSwx70enZSjiu24yDgRXbK2ZYjClwOdfwC+YFw5mweeT434hcxavVs5tDgZeuVg+wMVVGVBSckh3LVKG9ll1DU8JGd6Ux3LvVPb6WVqYWwk7IaRTKZ7tOSSGt/kL0GI4broPeiKXD2vBgwhL2w5XlCjdWQ0ykJkZaL1oCSaW+Uw6c8iOXvA09rHNndKKxjJI2VaxUK5ReWmImQ9cGrVm2sT+tWS6zI9J9vZg5GjO7db7ETczDagGmlTSd4WpArIK+lO0ox3Hi5IXBfSCyGhiPh7svlCWPhlkvZaPahh0buDyYRfR7jRf4cBG3b7GdvrGhnlOQCWCwjKIhAXzzCJQDJLjzHsfveoT9g5WsOx15cjuPi3YxgfRjlbPtNONO3gKy2auSHkB+wgfAMeRfIwKP+N8lSyWeVuasyRKZ0ckP4xmFtnqVBHZRJZpPRLMp6ZLmzoyIM1DGqn0rPcMkx31jtjp7bgknp+PNgXW+azYqSg2mTPJTHBF+Ar0J4e0/17obe+wfCGD54L9N4re2f23OR56B27CIUHnCqVEEEa3KSc655DciHweExR6ZdO06LNN+g4A+DmhUtLPjhLJqnF84mRuuDoSK6fUyYdaIST2NEnUgHRXLx4aj0vCs/+okgR+KWI7f/Qkt8vE5mnVPPZPWXTOiTijYdJKYifrvrcz0=
